server: 
  port: 8010
spring:
  cloud:
    gateway:
      routes:
        - id: movieRouter
          uri: lb://MOVIES
          predicates:
           - Path=/movies/
        - id: catalogRouter
          uri: lb://CATALOG
          predicates:
           - Path=/catalog/**
  
